FROM python:3.9 
WORKDIR /app 
COPY requirements.txt . 
RUN pip install -r requirements.txt 
COPY app.py . 
Microsoft Windows [Version 10.0.22631.5768]
(c) Microsoft Corporation. All rights reserved.

C:\Users\vigne\ShopEase\backend>C:\Users\vigne\ShopEase\backend>C:\Users\vigne\ShopEase\backend>C:\Users\vigne\ShopEase\backend>C:\Users\vigne\ShopEase\backend>
C:\Users\vigne\ShopEase\backend>[H[2J[3J
C:\Users\vigne\ShopEase\backend>
C:\Users\vigne\ShopEase>