apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopease-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopease
  template:
    metadata:
      labels:
        app: shopease
    spec:
      containers:
      - name: shopease
        image: ghcr.io/suryascalezee/shopease:latest
        ports:
        - containerPort: 8000
