apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopease-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: shopease.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopease-service
                port:
                  number: 80
