name: CI - Build & Push & Update K8s

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: shopease

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read image tag from values.yaml
        id: read_tag
        run: |
          IMAGE_TAG=$(yq '.image.tag' values.yaml)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.read_tag.outputs.IMAGE_TAG }}
          file: ./Dockerfile
          context: .

      - name: Update deployment manifest with new image tag
        run: |
          IMAGE="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.read_tag.outputs.IMAGE_TAG }}"
          echo "Using image $IMAGE"
          sed -i "s|image: .*|image: $IMAGE|" k8s/deployment.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "ci: update k8s image to tag ${{ steps.read_tag.outputs.IMAGE_TAG }}" || echo "no changes to commit"
          git push
