name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "❌ DOCKER_USERNAME is missing"
            exit 1
          else
            echo "✅ DOCKER_USERNAME is set"
          fi

          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "❌ DOCKER_PASSWORD is missing"
            exit 1
          else
            echo "✅ DOCKER_PASSWORD is set"
          fi

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up tags
        run: |
          echo "IMAGE=suryascalezee/shopease" >> $GITHUB_ENV
          echo "TAG_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "TAG_LATEST=latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE:$TAG_LATEST -t $IMAGE:$TAG_SHA .

      - name: Push Docker image
        run: |
          docker push $IMAGE:$TAG_LATEST
          docker push $IMAGE:$TAG_SHA
