name: CI - Build & Push & Update K8s

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: shopease

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ suryascalezee }}
          password: ${{ Scalezee@123 }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          context: .

      - name: Update deployment manifest with new image tag
        run: |
          IMAGE="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "Using image $IMAGE"
          sed -i "s|image: .*|image: $IMAGE|" k8s/deployment.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "ci: update k8s image to ${{ github.sha }}" || echo "no changes to commit"
          git push
